### ISSUE TITLE
schedules

### ISSUE THREAD

**Issue by jmonster** [project-badass/thermal#4]
+ 1 day schedule
+ weekday/weekend schedule
+ 7 day schedule
+ persist/load from EEPROM
+ sync with cloud

Schedules:
7 days, 96 15-minute intervals, temperature between 50 and 100

7 days in first 3 bits 000 through 111

96 requires 7 bits
Temperature value requires 

50 degrees requires 6 bits (000000 through 110010

---

16 bits per schedule; so 2 bytes -- call it a "short int"

DDD TTTTTTT SSSSSS

**Comment by jmonster** [comment]
https://docs.particle.io/reference/firmware/photon/#particle-synctime-

**Comment by tupakapoor** [comment]
Walking through scheduling on the app for my thermostat - if you choose "Yes" for the "is someone home all day" it skips the leaving and returning steps 
![img_1045 1](https://cloud.githubusercontent.com/assets/2296412/25582585/0eae9990-2e5c-11e7-8d2a-6f416edfb630.jpg)
![img_1046 1](https://cloud.githubusercontent.com/assets/2296412/25582589/0f1c3158-2e5c-11e7-946e-9b2563846073.jpg)
![img_1047 1](https://cloud.githubusercontent.com/assets/2296412/25582588/0f1baa08-2e5c-11e7-94bf-fc73ecade0dd.jpg)
![img_1048 1](https://cloud.githubusercontent.com/assets/2296412/25582590/0f2013e0-2e5c-11e7-99a5-5b5b9de511ed.jpg)
![img_1049 1](https://cloud.githubusercontent.com/assets/2296412/25582591/0f22e37c-2e5c-11e7-9fb4-cb36021c2ebb.jpg)
![img_1050 1](https://cloud.githubusercontent.com/assets/2296412/25582587/0f1b7bc8-2e5c-11e7-9c42-ca5332684223.jpg)
![img_1051 1](https://cloud.githubusercontent.com/assets/2296412/25582586/0ee6e278-2e5c-11e7-81c2-07d4e5674855.jpg)
![img_1052 1](https://cloud.githubusercontent.com/assets/2296412/25582592/0f272b26-2e5c-11e7-962a-580502fe795f.jpg)
![img_1053 1](https://cloud.githubusercontent.com/assets/2296412/25582593/0f5c85dc-2e5c-11e7-8d79-006699be9d7c.jpg)
![img_1054 1](https://cloud.githubusercontent.com/assets/2296412/25582594/0f5ee2c8-2e5c-11e7-88b2-744045fe896a.jpg)
